// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v5.29.3
// source: products/understanding/ast/ast_service.proto

package ast

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ASTServiceClient is the client API for ASTService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ASTServiceClient interface {
	Translate(ctx context.Context, opts ...grpc.CallOption) (ASTService_TranslateClient, error)
}

type aSTServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewASTServiceClient(cc grpc.ClientConnInterface) ASTServiceClient {
	return &aSTServiceClient{cc}
}

func (c *aSTServiceClient) Translate(ctx context.Context, opts ...grpc.CallOption) (ASTService_TranslateClient, error) {
	stream, err := c.cc.NewStream(ctx, &ASTService_ServiceDesc.Streams[0], "/data.speech.ast.ASTService/Translate", opts...)
	if err != nil {
		return nil, err
	}
	x := &aSTServiceTranslateClient{stream}
	return x, nil
}

type ASTService_TranslateClient interface {
	Send(*TranslateRequest) error
	Recv() (*TranslateResponse, error)
	grpc.ClientStream
}

type aSTServiceTranslateClient struct {
	grpc.ClientStream
}

func (x *aSTServiceTranslateClient) Send(m *TranslateRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *aSTServiceTranslateClient) Recv() (*TranslateResponse, error) {
	m := new(TranslateResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ASTServiceServer is the server API for ASTService service.
// All implementations must embed UnimplementedASTServiceServer
// for forward compatibility
type ASTServiceServer interface {
	Translate(ASTService_TranslateServer) error
	mustEmbedUnimplementedASTServiceServer()
}

// UnimplementedASTServiceServer must be embedded to have forward compatible implementations.
type UnimplementedASTServiceServer struct {
}

func (UnimplementedASTServiceServer) Translate(ASTService_TranslateServer) error {
	return status.Errorf(codes.Unimplemented, "method Translate not implemented")
}
func (UnimplementedASTServiceServer) mustEmbedUnimplementedASTServiceServer() {}

// UnsafeASTServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ASTServiceServer will
// result in compilation errors.
type UnsafeASTServiceServer interface {
	mustEmbedUnimplementedASTServiceServer()
}

func RegisterASTServiceServer(s grpc.ServiceRegistrar, srv ASTServiceServer) {
	s.RegisterService(&ASTService_ServiceDesc, srv)
}

func _ASTService_Translate_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ASTServiceServer).Translate(&aSTServiceTranslateServer{stream})
}

type ASTService_TranslateServer interface {
	Send(*TranslateResponse) error
	Recv() (*TranslateRequest, error)
	grpc.ServerStream
}

type aSTServiceTranslateServer struct {
	grpc.ServerStream
}

func (x *aSTServiceTranslateServer) Send(m *TranslateResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *aSTServiceTranslateServer) Recv() (*TranslateRequest, error) {
	m := new(TranslateRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ASTService_ServiceDesc is the grpc.ServiceDesc for ASTService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ASTService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "data.speech.ast.ASTService",
	HandlerType: (*ASTServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Translate",
			Handler:       _ASTService_Translate_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "products/understanding/ast/ast_service.proto",
}
