// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v5.29.3
// source: common/rpcmeta.proto

package rpcmeta

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RequestMeta struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Required.
	// Backend endpoint name. Gateway will also use it to infer HTTP/WebSocket URL
	// path.
	Endpoint string `protobuf:"bytes,1,opt,name=Endpoint,json=endpoint,proto3" json:"Endpoint,omitempty"`
	// Required.
	// For historical reasons, this can be either a volcanic appid or a sail
	// platform appKey. If both are transmitted at the same time, you need to put
	// the volcengine appid in the AppID
	AppKey string `protobuf:"bytes,2,opt,name=AppKey,json=app_key,proto3" json:"AppKey,omitempty"`
	// Optional.
	// appID in volcengine
	AppID string `protobuf:"bytes,3,opt,name=AppID,json=app_id,proto3" json:"AppID,omitempty"`
	// - Required by gateway, you must provide a ResourceID on calling gateway.
	// - Optional for backend services, gateway doesn't need to pass this to
	// backend.
	ResourceID string `protobuf:"bytes,4,opt,name=ResourceID,json=resource_id,proto3" json:"ResourceID,omitempty"`
	// Required for Websocket connection (SDK -> Gateway), optional otherwise.
	// In websocket communication, a connection can be reused for multiple
	// simultaneous sessions. Servers use this ID mainly for debugging purposes.
	ConnectionID string `protobuf:"bytes,5,opt,name=ConnectionID,json=connection_id,proto3" json:"ConnectionID,omitempty"`
	// Required. Session is the minimum unit that performs a specific task. The
	// request data in a session can be devided into a number data packets
	// transmitted (but not necessarily processed by the server) in a sequential
	// manner. Each data packet can be denoted by a "Sequence" number (although
	// populating the "Sequence" field is not mandatory). In the simplest case,
	// all request data in a session is sent as a lump (ie, only one packet).
	SessionID string `protobuf:"bytes,6,opt,name=SessionID,json=session_id,proto3" json:"SessionID,omitempty"`
	// Optional, if not passed, default value 0 will be assumed. For streaming
	// RPC, this field can be omitted (because the order of sending is preserved
	// at the receiving side) unless the client needs the acknowledgement of
	// packet receipt from the server side.
	Sequence int32 `protobuf:"varint,7,opt,name=Sequence,json=sequence,proto3" json:"Sequence,omitempty"`
}

func (x *RequestMeta) Reset() {
	*x = RequestMeta{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_rpcmeta_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestMeta) ProtoMessage() {}

func (x *RequestMeta) ProtoReflect() protoreflect.Message {
	mi := &file_common_rpcmeta_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestMeta.ProtoReflect.Descriptor instead.
func (*RequestMeta) Descriptor() ([]byte, []int) {
	return file_common_rpcmeta_proto_rawDescGZIP(), []int{0}
}

func (x *RequestMeta) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *RequestMeta) GetAppKey() string {
	if x != nil {
		return x.AppKey
	}
	return ""
}

func (x *RequestMeta) GetAppID() string {
	if x != nil {
		return x.AppID
	}
	return ""
}

func (x *RequestMeta) GetResourceID() string {
	if x != nil {
		return x.ResourceID
	}
	return ""
}

func (x *RequestMeta) GetConnectionID() string {
	if x != nil {
		return x.ConnectionID
	}
	return ""
}

func (x *RequestMeta) GetSessionID() string {
	if x != nil {
		return x.SessionID
	}
	return ""
}

func (x *RequestMeta) GetSequence() int32 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

type BillingItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Required.
	// Billing unit, eg:
	// - minute (billed by the number of minutes used)
	// - word (billed by the number of words submitted or generated)
	// - call (billed by the number of RPC/HTTP/Websocket calls)
	Unit string `protobuf:"bytes,1,opt,name=Unit,json=unit,proto3" json:"Unit,omitempty"`
	// Optional.
	// The amount that the consumer consumed counted by `BillingItem.Unit`. We use
	// a float number because sometimes we want precision better than whole
	// numbers.
	Quantity float32 `protobuf:"fixed32,2,opt,name=Quantity,json=quantity,proto3" json:"Quantity,omitempty"`
}

func (x *BillingItem) Reset() {
	*x = BillingItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_rpcmeta_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BillingItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BillingItem) ProtoMessage() {}

func (x *BillingItem) ProtoReflect() protoreflect.Message {
	mi := &file_common_rpcmeta_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BillingItem.ProtoReflect.Descriptor instead.
func (*BillingItem) Descriptor() ([]byte, []int) {
	return file_common_rpcmeta_proto_rawDescGZIP(), []int{1}
}

func (x *BillingItem) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

func (x *BillingItem) GetQuantity() float32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type Billing struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Optional.
	// For new billing items, use this field. This is a list because there may be
	// more than one billing items in one request/session.
	Items []*BillingItem `protobuf:"bytes,1,rep,name=Items,json=items,proto3" json:"Items,omitempty"`
	// Optional.
	// For commodities that are priced w.r.t (typically audio/video) duration in
	// milliseconds.
	DurationMsec int64 `protobuf:"varint,2,opt,name=DurationMsec,json=duration_msec,proto3" json:"DurationMsec,omitempty"`
	// Optional.
	// For commodities priced w.r.t text length (number of words/tokens).
	WordCount int64 `protobuf:"varint,3,opt,name=WordCount,json=word_count,proto3" json:"WordCount,omitempty"`
}

func (x *Billing) Reset() {
	*x = Billing{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_rpcmeta_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Billing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Billing) ProtoMessage() {}

func (x *Billing) ProtoReflect() protoreflect.Message {
	mi := &file_common_rpcmeta_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Billing.ProtoReflect.Descriptor instead.
func (*Billing) Descriptor() ([]byte, []int) {
	return file_common_rpcmeta_proto_rawDescGZIP(), []int{2}
}

func (x *Billing) GetItems() []*BillingItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *Billing) GetDurationMsec() int64 {
	if x != nil {
		return x.DurationMsec
	}
	return 0
}

func (x *Billing) GetWordCount() int64 {
	if x != nil {
		return x.WordCount
	}
	return 0
}

type ResponseMeta struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Required.
	// The same SessionID in RequestMeta.
	SessionID string `protobuf:"bytes,1,opt,name=SessionID,json=session_id,proto3" json:"SessionID,omitempty"`
	// Optional.
	// The same sequence in RequestMeta (except that server *may* turn a positive
	// sequence to its negative counterpart).
	Sequence int32 `protobuf:"varint,2,opt,name=Sequence,json=sequence,proto3" json:"Sequence,omitempty"`
	// Optional.
	// Response status code.
	StatusCode int32 `protobuf:"varint,3,opt,name=StatusCode,json=status_code,proto3" json:"StatusCode,omitempty"`
	// Optional.
	// Detailed status information.
	Message string `protobuf:"bytes,4,opt,name=Message,json=message,proto3" json:"Message,omitempty"`
	// Billing information in case only backend servers can collect this
	// information.
	Billing *Billing `protobuf:"bytes,5,opt,name=Billing,json=billing,proto3,oneof" json:"Billing,omitempty"`
}

func (x *ResponseMeta) Reset() {
	*x = ResponseMeta{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_rpcmeta_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponseMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseMeta) ProtoMessage() {}

func (x *ResponseMeta) ProtoReflect() protoreflect.Message {
	mi := &file_common_rpcmeta_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseMeta.ProtoReflect.Descriptor instead.
func (*ResponseMeta) Descriptor() ([]byte, []int) {
	return file_common_rpcmeta_proto_rawDescGZIP(), []int{3}
}

func (x *ResponseMeta) GetSessionID() string {
	if x != nil {
		return x.SessionID
	}
	return ""
}

func (x *ResponseMeta) GetSequence() int32 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *ResponseMeta) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *ResponseMeta) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ResponseMeta) GetBilling() *Billing {
	if x != nil {
		return x.Billing
	}
	return nil
}

var File_common_rpcmeta_proto protoreflect.FileDescriptor

var file_common_rpcmeta_proto_rawDesc = []byte{
	0x0a, 0x14, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x72, 0x70, 0x63, 0x6d, 0x65, 0x74, 0x61,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x12, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x73, 0x70, 0x65,
	0x65, 0x63, 0x68, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x22, 0xda, 0x01, 0x0a, 0x0b, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x4d, 0x65, 0x74, 0x61, 0x12, 0x1a, 0x0a, 0x08, 0x45, 0x6e,
	0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x65, 0x6e,
	0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x12, 0x17, 0x0a, 0x06, 0x41, 0x70, 0x70, 0x4b, 0x65, 0x79,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x70, 0x70, 0x5f, 0x6b, 0x65, 0x79, 0x12,
	0x15, 0x0a, 0x05, 0x41, 0x70, 0x70, 0x49, 0x44, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x61, 0x70, 0x70, 0x5f, 0x69, 0x64, 0x12, 0x1f, 0x0a, 0x0a, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72,
	0x63, 0x65, 0x49, 0x44, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x72, 0x65, 0x73, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x12, 0x23, 0x0a, 0x0c, 0x43, 0x6f, 0x6e, 0x6e, 0x65,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x63,
	0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x12, 0x1d, 0x0a, 0x09,
	0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0a, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x53,
	0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x73,
	0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65, 0x22, 0x3d, 0x0a, 0x0b, 0x42, 0x69, 0x6c, 0x6c, 0x69,
	0x6e, 0x67, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x12, 0x0a, 0x04, 0x55, 0x6e, 0x69, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x6e, 0x69, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x51, 0x75,
	0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x08, 0x71, 0x75,
	0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x22, 0x84, 0x01, 0x0a, 0x07, 0x42, 0x69, 0x6c, 0x6c, 0x69,
	0x6e, 0x67, 0x12, 0x35, 0x0a, 0x05, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x1f, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x73, 0x70, 0x65, 0x65, 0x63, 0x68, 0x2e,
	0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x42, 0x69, 0x6c, 0x6c, 0x69, 0x6e, 0x67, 0x49, 0x74,
	0x65, 0x6d, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x12, 0x23, 0x0a, 0x0c, 0x44, 0x75, 0x72,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4d, 0x73, 0x65, 0x63, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x0d, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x6d, 0x73, 0x65, 0x63, 0x12, 0x1d,
	0x0a, 0x09, 0x57, 0x6f, 0x72, 0x64, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x0a, 0x77, 0x6f, 0x72, 0x64, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0xcc, 0x01,
	0x0a, 0x0c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x4d, 0x65, 0x74, 0x61, 0x12, 0x1d,
	0x0a, 0x09, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0a, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x12, 0x1a, 0x0a,
	0x08, 0x53, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x08, 0x73, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65, 0x12, 0x1f, 0x0a, 0x0a, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x12, 0x3a, 0x0a, 0x07, 0x42, 0x69, 0x6c, 0x6c, 0x69, 0x6e, 0x67, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x73, 0x70, 0x65,
	0x65, 0x63, 0x68, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x42, 0x69, 0x6c, 0x6c, 0x69,
	0x6e, 0x67, 0x48, 0x00, 0x52, 0x07, 0x62, 0x69, 0x6c, 0x6c, 0x69, 0x6e, 0x67, 0x88, 0x01, 0x01,
	0x42, 0x0a, 0x0a, 0x08, 0x5f, 0x42, 0x69, 0x6c, 0x6c, 0x69, 0x6e, 0x67, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_common_rpcmeta_proto_rawDescOnce sync.Once
	file_common_rpcmeta_proto_rawDescData = file_common_rpcmeta_proto_rawDesc
)

func file_common_rpcmeta_proto_rawDescGZIP() []byte {
	file_common_rpcmeta_proto_rawDescOnce.Do(func() {
		file_common_rpcmeta_proto_rawDescData = protoimpl.X.CompressGZIP(file_common_rpcmeta_proto_rawDescData)
	})
	return file_common_rpcmeta_proto_rawDescData
}

var file_common_rpcmeta_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_common_rpcmeta_proto_goTypes = []interface{}{
	(*RequestMeta)(nil),  // 0: data.speech.common.RequestMeta
	(*BillingItem)(nil),  // 1: data.speech.common.BillingItem
	(*Billing)(nil),      // 2: data.speech.common.Billing
	(*ResponseMeta)(nil), // 3: data.speech.common.ResponseMeta
}
var file_common_rpcmeta_proto_depIdxs = []int32{
	1, // 0: data.speech.common.Billing.Items:type_name -> data.speech.common.BillingItem
	2, // 1: data.speech.common.ResponseMeta.Billing:type_name -> data.speech.common.Billing
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_common_rpcmeta_proto_init() }
func file_common_rpcmeta_proto_init() {
	if File_common_rpcmeta_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_common_rpcmeta_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestMeta); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_rpcmeta_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BillingItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_rpcmeta_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Billing); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_rpcmeta_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResponseMeta); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_common_rpcmeta_proto_msgTypes[3].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_common_rpcmeta_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_rpcmeta_proto_goTypes,
		DependencyIndexes: file_common_rpcmeta_proto_depIdxs,
		MessageInfos:      file_common_rpcmeta_proto_msgTypes,
	}.Build()
	File_common_rpcmeta_proto = out.File
	file_common_rpcmeta_proto_rawDesc = nil
	file_common_rpcmeta_proto_goTypes = nil
	file_common_rpcmeta_proto_depIdxs = nil
}
